'use server';
/**
 * @fileOverview AI-powered product description augmentation flow.
 *
 * This file defines a Genkit flow that takes a basic product description as input and uses an AI model to enhance and elaborate on it, providing a more compelling and informative description for potential customers.
 *
 * @exports `enhanceProductDescription` - An async function that accepts a product description and returns an enhanced version.
 * @exports `EnhanceProductDescriptionInput` - The input type for the `enhanceProductDescription` function.
 * @exports `EnhanceProductDescriptionOutput` - The output type for the `enhanceProductDescription` function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

// Define the input schema for the product description.
const EnhanceProductDescriptionInputSchema = z.object({
  productDescription: z
    .string()
    .describe('A basic product description to be enhanced by AI.'),
});
export type EnhanceProductDescriptionInput = z.infer<
  typeof EnhanceProductDescriptionInputSchema
>;

// Define the output schema for the enhanced product description.
const EnhanceProductDescriptionOutputSchema = z.object({
  enhancedProductDescription: z
    .string()
    .describe('An enhanced and elaborated product description generated by AI.'),
});
export type EnhanceProductDescriptionOutput = z.infer<
  typeof EnhanceProductDescriptionOutputSchema
>;

// Define the main function that will be called to enhance the product description.
export async function enhanceProductDescription(
  input: EnhanceProductDescriptionInput
): Promise<EnhanceProductDescriptionOutput> {
  return enhanceProductDescriptionFlow(input);
}

// Define the Genkit prompt to generate the enhanced product description.
const enhanceProductDescriptionPrompt = ai.definePrompt({
  name: 'enhanceProductDescriptionPrompt',
  input: {schema: EnhanceProductDescriptionInputSchema},
  output: {schema: EnhanceProductDescriptionOutputSchema},
  prompt: `You are an AI assistant designed to improve product descriptions.

  Given a basic product description, your task is to enhance and elaborate on it to make it more compelling and informative for potential customers. Add details about features, benefits, and use cases.

  Basic Product Description: {{{productDescription}}}

  Enhanced Product Description:`,
});

// Define the Genkit flow for enhancing the product description.
const enhanceProductDescriptionFlow = ai.defineFlow(
  {
    name: 'enhanceProductDescriptionFlow',
    inputSchema: EnhanceProductDescriptionInputSchema,
    outputSchema: EnhanceProductDescriptionOutputSchema,
  },
  async input => {
    const {output} = await enhanceProductDescriptionPrompt(input);
    return output!;
  }
);
